version: '3.9'

services:
  mongo:
    image: mongo:7
    container_name: mediconnect-mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - mediconnect-net

  redis:
    image: redis:7-alpine
    container_name: mediconnect-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - mediconnect-net

  api:
    build:
      context: ./apps/api
    container_name: mediconnect-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis
    networks:
      - mediconnect-net

networks:
  mediconnect-net:
    driver: bridge

volumes:
  mongo-data:
  redis-data:
