import { useState, useEffect, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import QRCode from 'qrcode';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import StatusChip from '../../components/ui/StatusChip';
import { useIsMobile } from '../../hooks/useIsMobile';
import { getPatientByUserId, updatePatientByUserId } from '../../api/patients';
import { getAppointments } from '../../api/appointments';
import { getPrescriptions } from '../../api/prescriptions';
import { searchLabResults } from '../../api/labResults';

const BLOOD_TYPES = ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-'];

function RxQRSmall({ token }) {
  const ref = useRef(null);
  const url = `${window.location.origin}/rx/${token}`;
  useEffect(() => {
    if (ref.current) QRCode.toCanvas(ref.current, url, { width: 72, margin: 1, color: { dark: '#0fe3b0', light: '#0a1628' } });
  }, [url]);
  return <canvas ref={ref} style={{ borderRadius: 6, border: '1px solid rgba(15,227,176,0.2)', flexShrink: 0, cursor: 'pointer' }} onClick={() => window.open(url, '_blank')} title="Open verification page" />;
}

async function printRx(rx) {
  let qrImg = '';
  if (rx.verificationToken) {
    const url = `${window.location.origin}/rx/${rx.verificationToken}`;
    const dataUrl = await QRCode.toDataURL(url, { width: 120, margin: 1, color: { dark: '#000', light: '#fff' } });
    qrImg = `<img src="${dataUrl}" width="120" height="120" style="display:block" alt="QR" />`;
  }
  const el = document.createElement('div');
  el.id = '__rx_print__';
  el.innerHTML = `
    <style>@media not print{#__rx_print__{display:none}}@media print{body>*:not(#__rx_print__){display:none}}</style>
    <div style="font-family:Georgia,serif;padding:40px;max-width:620px;margin:0 auto;color:#000">
      <div style="display:flex;justify-content:space-between;border-bottom:2px solid #000;padding-bottom:14px;margin-bottom:20px">
        <div><h2 style="margin:0;font-size:22px">Salamtak</h2><p style="margin:4px 0 0;font-size:12px;color:#555">Digital Prescription</p></div>
        <div style="text-align:right;font-size:12px">
          <div>Date: ${new Date(rx.createdAt).toLocaleDateString()}</div>
          <div>RX-${String(rx._id).slice(-6).toUpperCase()}</div>
        </div>
      </div>
      <div style="margin-bottom:18px;font-size:13px"><strong>Patient:</strong> ${rx.patientId?.name || '—'}</div>
      <table style="width:100%;border-collapse:collapse;font-size:13px">
        <thead><tr style="background:#f5f5f5">
          ${['Medication','Dose','Frequency','Duration'].map(h=>`<th style="border:1px solid #ddd;padding:6px 10px;text-align:left">${h}</th>`).join('')}
        </tr></thead>
        <tbody>${(rx.medications||[]).map(m=>`<tr>${[m.name,m.dosage,m.frequency,m.duration].map(v=>`<td style="border:1px solid #ddd;padding:6px 10px">${v||'—'}</td>`).join('')}</tr>`).join('')}</tbody>
      </table>
      ${(rx.analyses||[]).length>0?`<div style="margin-top:18px"><strong style="font-size:13px">Lab Analysis Requests:</strong><ul style="margin:8px 0 0;padding-left:20px;font-size:13px">${rx.analyses.map(a=>`<li><strong>${a.name}</strong>${a.instructions?` — ${a.instructions}`:''}</li>`).join('')}</ul></div>`:''}
      ${rx.instructions?`<div style="margin-top:18px;font-size:13px"><strong>Notes:</strong> ${rx.instructions}</div>`:''}
      ${qrImg?`<div style="margin-top:28px;display:flex;align-items:center;gap:20px;border-top:1px solid #eee;padding-top:20px">${qrImg}<div style="font-size:11px;color:#555"><strong style="font-size:12px;color:#000">Verify this prescription</strong><br/>${window.location.origin}/rx/${rx.verificationToken}</div></div>`:''}
      <div style="margin-top:24px;border-top:1px solid #ccc;padding-top:14px;font-size:11px;color:#555;text-align:center">Generated by Salamtak · Digitally issued.</div>
    </div>`;
  document.body.appendChild(el);
  window.print();
  document.body.removeChild(el);
}

function calcAge(dob) {
  if (!dob) return null;
  return Math.floor((Date.now() - new Date(dob).getTime()) / (1000 * 60 * 60 * 24 * 365.25));
}

function refCode(id) {
  return '#P-' + String(id).slice(-4).toUpperCase();
}

function initials(name) {
  return name?.split(' ').filter(Boolean).slice(0, 2).map(w => w[0].toUpperCase()).join('') || '?';
}

function TagInput({ value, onChange, placeholder }) {
  const [input, setInput] = useState('');
  const add = () => {
    const trimmed = input.trim();
    if (trimmed && !value.includes(trimmed)) onChange([...value, trimmed]);
    setInput('');
  };
  return (
    <div style={{ border: '1px solid var(--border)', borderRadius: 8, padding: '6px 10px', background: 'var(--bg)', minHeight: 40 }}>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6, marginBottom: value.length ? 6 : 0 }}>
        {value.map(tag => (
          <span key={tag} style={{ display: 'inline-flex', alignItems: 'center', gap: 4, padding: '2px 8px', borderRadius: 20, background: 'var(--bg3)', border: '1px solid var(--border)', fontSize: 12, color: 'var(--text)' }}>
            {tag}
            <button onClick={() => onChange(value.filter(t => t !== tag))} style={{ background: 'none', border: 'none', color: 'var(--text3)', cursor: 'pointer', fontSize: 14, lineHeight: 1, padding: 0 }}>×</button>
          </span>
        ))}
      </div>
      <input
        value={input}
        onChange={e => setInput(e.target.value)}
        onKeyDown={e => { if (e.key === 'Enter') { e.preventDefault(); add(); } }}
        onBlur={add}
        placeholder={placeholder}
        style={{ border: 'none', outline: 'none', background: 'transparent', fontSize: 13, color: 'var(--text)', width: '100%' }}
      />
    </div>
  );
}

const TABS = ['overview', 'appointments', 'prescriptions', 'labs', 'summary'];
const TAB_LABELS = { overview: 'Overview', appointments: 'Appointments', prescriptions: 'Prescriptions', labs: 'Lab Results', summary: 'AI Summary' };

export default function PatientDetailPage() {
  const { userId } = useParams();
  const navigate = useNavigate();
  const { t } = useTranslation();
  const isMobile = useIsMobile();

  const [tab, setTab] = useState('overview');
  const [profile, setProfile] = useState(null);
  const [patientName, setPatientName] = useState('');
  const [appointments, setAppointments] = useState([]);
  const [prescriptions, setPrescriptions] = useState([]);
  const [labResults, setLabResults] = useState([]);
  const [expandedAppt, setExpandedAppt] = useState(null);
  const [loading, setLoading] = useState(true);
  const [editMode, setEditMode]   = useState(false);
  const [draft, setDraft]         = useState(null);
  const [saving, setSaving]       = useState(false);
  const [saveError, setSaveError] = useState(null);

  useEffect(() => {
    setLoading(true);
    Promise.allSettled([
      getPatientByUserId(userId).then(setProfile),
      getAppointments({ patientId: userId }).then(data => {
        const list = Array.isArray(data) ? data : data?.data ?? [];
        setAppointments([...list].sort((a, b) => new Date(b.date) - new Date(a.date)));
        if (list[0]?.patientId?.name) setPatientName(list[0].patientId.name);
      }),
      getPrescriptions({ patientId: userId }).then(data => {
        const list = Array.isArray(data?.data) ? data.data : Array.isArray(data) ? data : [];
        setPrescriptions([...list].sort((a, b) => new Date(b.createdAt) - new Date(a.createdAt)));
      }),
      searchLabResults({ patientId: userId }).then(data => {
        const list = Array.isArray(data?.data) ? data.data : Array.isArray(data) ? data : [];
        setLabResults([...list].sort((a, b) => new Date(b.issuedAt || b.createdAt) - new Date(a.issuedAt || a.createdAt)));
      }),
    ]).finally(() => setLoading(false));
  }, [userId]);

  const startEdit = () => {
    setDraft({
      bloodType:     profile?.bloodType     || '',
      dateOfBirth:   profile?.dateOfBirth   ? new Date(profile.dateOfBirth).toISOString().slice(0, 10) : '',
      allergies:     profile?.allergies     ? [...profile.allergies]     : [],
      conditions:    profile?.conditions    ? [...profile.conditions]    : [],
      medicalHistory:profile?.medicalHistory? [...profile.medicalHistory]: [],
    });
    setSaveError(null);
    setEditMode(true);
  };

  const cancelEdit = () => {
    setEditMode(false);
    setDraft(null);
    setSaveError(null);
  };

  const saveEdit = async () => {
    setSaving(true);
    setSaveError(null);
    try {
      const payload = {};
      if (draft.bloodType)   payload.bloodType   = draft.bloodType;
      if (draft.dateOfBirth) payload.dateOfBirth = draft.dateOfBirth;
      payload.allergies      = draft.allergies;
      payload.conditions     = draft.conditions;
      payload.medicalHistory = draft.medicalHistory;
      const updated = await updatePatientByUserId(userId, payload);
      setProfile(updated);
      setEditMode(false);
      setDraft(null);
    } catch (err) {
      setSaveError(err?.response?.data?.message || 'فشل الحفظ، حاول مجدداً');
    } finally {
      setSaving(false);
    }
  };

  const displayName = patientName || profile?.userId?.name || '…';
  const age = profile?.dateOfBirth ? calcAge(profile.dateOfBirth) : null;

  const activeAppt = appointments.find(a => ['confirmed', 'in_progress'].includes(a.status));

  return (
    <div>
      {/* Sticky header */}
      <div style={{ position: 'sticky', top: 0, zIndex: 10, background: 'rgba(6,13,24,0.92)', backdropFilter: 'blur(14px)', borderBottom: '1px solid var(--border)', padding: isMobile ? '12px 14px' : '14px 26px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: 14, flexWrap: 'wrap' }}>
          <button onClick={() => navigate('/patients')} style={{ background: 'var(--bg3)', border: '1px solid var(--border)', borderRadius: 8, padding: '6px 12px', color: 'var(--text2)', fontSize: 12, cursor: 'pointer' }}>
            ← Patients
          </button>
          <div style={{ flex: 1 }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
              <div style={{ width: 36, height: 36, borderRadius: 9, background: 'linear-gradient(135deg,var(--mint),#0891b2)', display: 'grid', placeItems: 'center', fontSize: 13, fontWeight: 700, color: '#fff', flexShrink: 0 }}>
                {initials(displayName)}
              </div>
              <div>
                <div style={{ fontFamily: 'var(--font-display)', fontSize: 18, fontWeight: 500 }}>{displayName}</div>
                <div style={{ fontSize: 11.5, color: 'var(--text2)' }}>
                  {[age ? `${age}y` : null, profile?.bloodType || null, refCode(userId)].filter(Boolean).join(' · ')}
                </div>
              </div>
            </div>
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            {activeAppt && (
              <>
                <button
                  onClick={() => navigate(`/appointments/${activeAppt._id}/chat`, { state: { otherPartyName: displayName } })}
                  style={{ background: 'var(--mint-dim)', border: '1px solid rgba(15,227,176,0.3)', borderRadius: 8, padding: '7px 13px', color: 'var(--mint)', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
                >
                  Chat
                </button>
                {activeAppt.status === 'confirmed' && (
                  <button
                    onClick={() => navigate(`/appointments/${activeAppt._id}/video`, { state: { otherPartyName: displayName } })}
                    style={{ background: 'rgba(124,58,237,0.12)', border: '1px solid rgba(124,58,237,0.3)', borderRadius: 8, padding: '7px 13px', color: '#a78bfa', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
                  >
                    🎥 Video
                  </button>
                )}
              </>
            )}
            <Button style={{ padding: '7px 14px', fontSize: 12 }} onClick={() => navigate('/prescriptions', { state: { patientId: userId, patientName: displayName } })}>
              + Prescribe
            </Button>
          </div>
        </div>

        {/* Allergy banner */}
        {(profile?.allergies?.length > 0) && (
          <div style={{ marginTop: 10, background: 'rgba(244,63,94,0.1)', border: '1px solid rgba(244,63,94,0.3)', borderRadius: 8, padding: '8px 14px', display: 'flex', alignItems: 'center', gap: 8 }}>
            <span style={{ fontSize: 15 }}>⚠️</span>
            <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--rose)' }}>Allergies: </span>
            <span style={{ fontSize: 12, color: 'var(--rose)' }}>{profile.allergies.join(', ')}</span>
          </div>
        )}
      </div>

      <div style={{ padding: isMobile ? 14 : 26 }}>
        {/* Tabs */}
        <div style={{ display: 'flex', gap: 4, marginBottom: 22, borderBottom: '1px solid var(--border)', paddingBottom: 12, flexWrap: 'wrap' }}>
          {TABS.map(key => (
            <button key={key} onClick={() => setTab(key)}
              style={{ padding: '6px 16px', borderRadius: 8, border: '1px solid', cursor: 'pointer', fontSize: 13, fontWeight: 500, transition: 'all .12s',
                background: tab === key ? 'var(--mint-dim)' : 'transparent',
                borderColor: tab === key ? 'rgba(15,227,176,0.2)' : 'transparent',
                color: tab === key ? 'var(--mint)' : 'var(--text2)' }}>
              {TAB_LABELS[key]}
              {key === 'appointments' && appointments.length > 0 && (
                <span style={{ marginLeft: 6, background: 'var(--bg3)', border: '1px solid var(--border)', borderRadius: 20, padding: '1px 6px', fontSize: 10.5, color: 'var(--text2)' }}>{appointments.length}</span>
              )}
            </button>
          ))}
        </div>

        {loading && <div style={{ color: 'var(--text2)', fontSize: 13 }}>Loading…</div>}

        {!loading && tab === 'overview' && (
          <div style={{ display: 'grid', gridTemplateColumns: isMobile ? '1fr' : '1fr 1fr', gap: 16 }}>
            {/* Health profile */}
            <Card>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}>
                <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text3)' }}>Health Profile</div>
                {!editMode && profile && (
                  <button onClick={startEdit} style={{ fontSize: 12, padding: '4px 12px', borderRadius: 8, border: '1px solid var(--border)', background: 'transparent', color: 'var(--text2)', cursor: 'pointer' }}>
                    Edit Profile
                  </button>
                )}
              </div>

              {!editMode ? (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                  {[
                    ['Date of Birth', profile?.dateOfBirth ? new Date(profile.dateOfBirth).toLocaleDateString() : '—'],
                    ['Age', age ? `${age} years` : '—'],
                    ['Blood Type', profile?.bloodType || '—'],
                    ['Ref', refCode(userId)],
                  ].map(([label, val]) => (
                    <div key={label} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '8px 0', borderBottom: '1px solid var(--border)' }}>
                      <span style={{ fontSize: 12, color: 'var(--text2)' }}>{label}</span>
                      <span style={{ fontSize: 13, fontWeight: 500 }}>{val}</span>
                    </div>
                  ))}
                  {profile?.allergies?.length > 0 && (
                    <div>
                      <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--rose)', marginBottom: 6 }}>⚠ Allergies</div>
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                        {profile.allergies.map(a => (
                          <span key={a} style={{ padding: '2px 10px', borderRadius: 20, background: 'rgba(244,63,94,0.1)', border: '1px solid rgba(244,63,94,0.3)', fontSize: 12, color: 'var(--rose)' }}>{a}</span>
                        ))}
                      </div>
                    </div>
                  )}
                  {profile?.conditions?.length > 0 && (
                    <div>
                      <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--text3)', marginBottom: 6 }}>Conditions</div>
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                        {profile.conditions.map(c => (
                          <span key={c} style={{ padding: '2px 10px', borderRadius: 20, background: 'var(--bg3)', border: '1px solid var(--border)', fontSize: 12, color: 'var(--text2)' }}>{c}</span>
                        ))}
                      </div>
                    </div>
                  )}
                  {profile?.medicalHistory?.length > 0 && (
                    <div>
                      <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--text3)', marginBottom: 6 }}>Medical History</div>
                      <div style={{ display: 'flex', flexWrap: 'wrap', gap: 6 }}>
                        {profile.medicalHistory.map(h => (
                          <span key={h} style={{ padding: '2px 10px', borderRadius: 20, background: 'var(--bg3)', border: '1px solid var(--border)', fontSize: 12, color: 'var(--text2)' }}>{h}</span>
                        ))}
                      </div>
                    </div>
                  )}
                  {!profile && <p style={{ fontSize: 12, color: 'var(--text3)' }}>No profile data available.</p>}
                </div>
              ) : (
                <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>
                  <div>
                    <label style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--text3)', display: 'block', marginBottom: 6 }}>Date of Birth</label>
                    <input type="date" value={draft.dateOfBirth}
                      onChange={e => setDraft(d => ({ ...d, dateOfBirth: e.target.value }))}
                      style={{ width: '100%', padding: '8px 10px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--bg)', color: 'var(--text)', fontSize: 13, boxSizing: 'border-box' }} />
                  </div>
                  <div>
                    <label style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--text3)', display: 'block', marginBottom: 6 }}>Blood Type</label>
                    <select value={draft.bloodType} onChange={e => setDraft(d => ({ ...d, bloodType: e.target.value }))}
                      style={{ width: '100%', padding: '8px 10px', borderRadius: 8, border: '1px solid var(--border)', background: 'var(--bg)', color: 'var(--text)', fontSize: 13 }}>
                      <option value="">— Select —</option>
                      {BLOOD_TYPES.map(bt => <option key={bt} value={bt}>{bt}</option>)}
                    </select>
                  </div>
                  <div>
                    <label style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--rose)', display: 'block', marginBottom: 6 }}>Allergies</label>
                    <TagInput value={draft.allergies} onChange={v => setDraft(d => ({ ...d, allergies: v }))} placeholder="Type and press Enter…" />
                  </div>
                  <div>
                    <label style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--text3)', display: 'block', marginBottom: 6 }}>Conditions</label>
                    <TagInput value={draft.conditions} onChange={v => setDraft(d => ({ ...d, conditions: v }))} placeholder="Type and press Enter…" />
                  </div>
                  <div>
                    <label style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', color: 'var(--text3)', display: 'block', marginBottom: 6 }}>Medical History</label>
                    <TagInput value={draft.medicalHistory} onChange={v => setDraft(d => ({ ...d, medicalHistory: v }))} placeholder="Type and press Enter…" />
                  </div>
                  {saveError && (
                    <div style={{ fontSize: 12, color: 'var(--rose)', padding: '8px 12px', borderRadius: 8, background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.2)' }}>
                      {saveError}
                    </div>
                  )}
                  <div style={{ display: 'flex', gap: 8, paddingTop: 4 }}>
                    <button onClick={saveEdit} disabled={saving}
                      style={{ flex: 1, padding: '9px 0', borderRadius: 8, border: 'none', background: 'var(--primary)', color: '#fff', fontSize: 13, fontWeight: 600, cursor: saving ? 'not-allowed' : 'pointer', opacity: saving ? 0.7 : 1 }}>
                      {saving ? 'جاري الحفظ…' : 'حفظ'}
                    </button>
                    <button onClick={cancelEdit} disabled={saving}
                      style={{ flex: 1, padding: '9px 0', borderRadius: 8, border: '1px solid var(--border)', background: 'transparent', color: 'var(--text2)', fontSize: 13, cursor: 'pointer' }}>
                      إلغاء
                    </button>
                  </div>
                </div>
              )}
            </Card>

            {/* Summary stats */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
              {[
                ['Total Appointments', appointments.length],
                ['Prescriptions', prescriptions.length],
                ['Lab Results', labResults.length],
                ['Last Visit', appointments[0] ? new Date(appointments[0].date).toLocaleDateString() : '—'],
              ].map(([label, value]) => (
                <div key={label} style={{ background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 10, padding: '14px 18px', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <span style={{ fontSize: 13, color: 'var(--text2)' }}>{label}</span>
                  <span style={{ fontSize: 16, fontWeight: 700 }}>{value}</span>
                </div>
              ))}
            </div>
          </div>
        )}

        {!loading && tab === 'appointments' && (
          <div>
            {appointments.length === 0 && <p style={{ fontSize: 13, color: 'var(--text3)' }}>No appointments found.</p>}
            {appointments.map(a => {
              const isExpanded = expandedAppt === a._id;
              const isActive = ['confirmed', 'in_progress'].includes(a.status);
              return (
                <div key={a._id}
                  style={{ background: 'var(--bg2)', border: `1px solid ${isActive ? 'var(--mint)' : 'var(--border)'}`, borderRadius: 10, marginBottom: 10, overflow: 'hidden', transition: 'border-color .15s' }}>
                  <div onClick={() => setExpandedAppt(isExpanded ? null : a._id)}
                    style={{ display: 'flex', alignItems: 'center', gap: 12, padding: '13px 16px', cursor: 'pointer' }}>
                    <div style={{ width: 8, height: 8, borderRadius: '50%', background: isActive ? 'var(--mint)' : 'var(--text3)', flexShrink: 0, boxShadow: isActive ? '0 0 0 3px var(--mint-dim)' : 'none' }} />
                    <div style={{ flex: 1, minWidth: 0 }}>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, flexWrap: 'wrap' }}>
                        <span style={{ fontSize: 13, fontWeight: 500, textTransform: 'capitalize' }}>{a.visitType || 'Consultation'}</span>
                        <StatusChip status={a.status} />
                      </div>
                      <div style={{ fontSize: 11.5, color: 'var(--text2)', marginTop: 3 }}>
                        {new Date(a.date).toLocaleDateString()} {a.timeSlot?.start ? `· ${a.timeSlot.start}` : ''}
                        {a.reason ? ` · ${a.reason}` : ''}
                      </div>
                    </div>
                    <span style={{ color: 'var(--text3)', fontSize: 12 }}>{isExpanded ? '▲' : '▼'}</span>
                  </div>

                  {isExpanded && (
                    <div style={{ borderTop: '1px solid var(--border)', padding: '14px 16px' }}>
                      {a.reason && (
                        <div style={{ marginBottom: 10 }}>
                          <div style={{ fontSize: 10.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em', color: 'var(--text2)', marginBottom: 4 }}>Reason</div>
                          <div style={{ fontSize: 13, color: 'var(--text)' }}>{a.reason}</div>
                        </div>
                      )}
                      <div style={{ fontSize: 10.5, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.07em', color: 'var(--text2)', marginBottom: 8 }}>Appointment ID</div>
                      <div style={{ fontSize: 11, fontFamily: 'var(--font-mono)', color: 'var(--text3)', marginBottom: 14 }}>{a._id}</div>
                      <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                        <button
                          onClick={() => navigate(`/appointments/${a._id}/chat`, { state: { otherPartyName: displayName } })}
                          style={{ background: 'var(--mint-dim)', border: '1px solid rgba(15,227,176,0.3)', borderRadius: 7, padding: '6px 13px', color: 'var(--mint)', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
                        >
                          Chat
                        </button>
                        {a.status === 'confirmed' && (
                          <button
                            onClick={() => navigate(`/appointments/${a._id}/video`, { state: { otherPartyName: displayName } })}
                            style={{ background: 'rgba(124,58,237,0.12)', border: '1px solid rgba(124,58,237,0.3)', borderRadius: 7, padding: '6px 13px', color: '#a78bfa', fontSize: 12, fontWeight: 600, cursor: 'pointer' }}
                          >
                            🎥 Video Call
                          </button>
                        )}
                        <button
                          onClick={() => navigate('/prescriptions', { state: { patientId: userId, patientName: displayName, appointmentId: a._id } })}
                          style={{ background: 'var(--bg3)', border: '1px solid var(--border)', borderRadius: 7, padding: '6px 13px', color: 'var(--text)', fontSize: 12, cursor: 'pointer' }}
                        >
                          + Prescription
                        </button>
                      </div>
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        )}

        {!loading && tab === 'prescriptions' && (
          <div>
            <div style={{ display: 'flex', justifyContent: 'flex-end', marginBottom: 14 }}>
              <Button style={{ padding: '7px 14px', fontSize: 12 }} onClick={() => navigate('/prescriptions', { state: { patientId: userId, patientName: displayName } })}>
                + New Prescription
              </Button>
            </div>
            {prescriptions.length === 0 && <p style={{ fontSize: 13, color: 'var(--text3)' }}>No prescriptions yet.</p>}
            {prescriptions.map(rx => (
              <Card key={rx._id} style={{ marginBottom: 12 }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 10 }}>
                  <div>
                    <div style={{ fontFamily: 'var(--font-mono)', fontSize: 10.5, color: 'var(--mint)', marginBottom: 2 }}>
                      RX-{String(rx._id).slice(-6).toUpperCase()}
                    </div>
                    <div style={{ fontSize: 11.5, color: 'var(--text2)' }}>
                      {new Date(rx.createdAt).toLocaleDateString()}
                      {rx.validUntil ? ` · Valid until ${new Date(rx.validUntil).toLocaleDateString()}` : ''}
                    </div>
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    {rx.verificationToken && <RxQRSmall token={rx.verificationToken} />}
                    <Button variant="ghost" style={{ padding: '4px 9px', fontSize: 11 }} onClick={() => printRx(rx)}>
                      🖨 Print
                    </Button>
                  </div>
                </div>

                {rx.medications?.length > 0 && (
                  <div style={{ marginBottom: 8 }}>
                    {rx.medications.map((m, i) => (
                      <div key={i} style={{ background: 'var(--bg3)', border: '1px solid var(--border)', borderRadius: 7, padding: '8px 12px', marginBottom: 6 }}>
                        <div style={{ fontSize: 13, fontWeight: 600 }}>{m.name}</div>
                        {(m.dosage || m.frequency || m.duration) && (
                          <div style={{ fontSize: 11.5, color: 'var(--text2)', marginTop: 2 }}>
                            {[m.dosage, m.frequency, m.duration].filter(Boolean).join(' · ')}
                          </div>
                        )}
                      </div>
                    ))}
                  </div>
                )}

                {rx.analyses?.length > 0 && (
                  <div style={{ marginBottom: 8 }}>
                    <div style={{ fontSize: 11, fontWeight: 600, textTransform: 'uppercase', letterSpacing: '0.07em', color: 'var(--text2)', marginBottom: 6 }}>Lab Requests</div>
                    {rx.analyses.map((a, i) => (
                      <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 12.5, marginBottom: 4 }}>
                        <span style={{ color: 'var(--amber)' }}>🧪</span>
                        <div>
                          <span style={{ fontWeight: 600 }}>{a.name}</span>
                          {a.instructions && <span style={{ color: 'var(--text2)' }}> — {a.instructions}</span>}
                        </div>
                      </div>
                    ))}
                  </div>
                )}

                {rx.instructions && (
                  <div style={{ fontSize: 12, color: 'var(--text2)', borderTop: '1px solid var(--border)', paddingTop: 8, marginTop: 4 }}>
                    {rx.instructions}
                  </div>
                )}
              </Card>
            ))}
          </div>
        )}

        {!loading && tab === 'labs' && (
          <div>
            {labResults.length === 0 && <p style={{ fontSize: 13, color: 'var(--text3)' }}>No lab results found.</p>}
            {labResults.map(lr => {
              const hasCritical = lr.tests?.some(t => t.flag === 'critical');
              const hasAbnormal = lr.tests?.some(t => ['high', 'low'].includes(t.flag));
              return (
                <Card key={lr._id} style={{ marginBottom: 12, borderColor: hasCritical ? 'rgba(244,63,94,0.4)' : undefined }}>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 }}>
                    <div>
                      <div style={{ fontSize: 13.5, fontWeight: 600 }}>{lr.labName || 'Lab Result'}</div>
                      <div style={{ fontSize: 11.5, color: 'var(--text2)', marginTop: 2 }}>
                        {lr.issuedAt ? new Date(lr.issuedAt).toLocaleDateString() : new Date(lr.createdAt).toLocaleDateString()}
                      </div>
                    </div>
                    {hasCritical && <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--rose)', background: 'rgba(244,63,94,0.1)', border: '1px solid rgba(244,63,94,0.3)', borderRadius: 6, padding: '3px 9px' }}>CRITICAL</span>}
                    {!hasCritical && hasAbnormal && <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--amber)', background: 'rgba(251,191,36,0.1)', border: '1px solid rgba(251,191,36,0.3)', borderRadius: 6, padding: '3px 9px' }}>ABNORMAL</span>}
                  </div>
                  {lr.tests?.length > 0 && (
                    <div style={{ display: 'grid', gap: 4 }}>
                      {lr.tests.map((test, i) => {
                        const flagColor = test.flag === 'critical' ? 'var(--rose)' : test.flag === 'normal' ? 'var(--mint)' : 'var(--amber)';
                        return (
                          <div key={i} style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '6px 10px', background: 'var(--bg3)', borderRadius: 6 }}>
                            <span style={{ fontSize: 12 }}>{test.name}</span>
                            <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                              {test.value && <span style={{ fontSize: 12, color: 'var(--text2)' }}>{test.value}{test.unit ? ` ${test.unit}` : ''}</span>}
                              {test.flag && <span style={{ fontSize: 10.5, fontWeight: 600, color: flagColor }}>{test.flag.toUpperCase()}</span>}
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                  {lr.notes && <div style={{ fontSize: 12, color: 'var(--text2)', marginTop: 10, paddingTop: 10, borderTop: '1px solid var(--border)' }}>{lr.notes}</div>}
                </Card>
              );
            })}
          </div>
        )}
        {!loading && tab === 'summary' && (() => {
          const latest   = profile?.latestHealthSummary;
          const history  = (profile?.healthSummaries || []).slice().reverse();

          if (!latest) return (
            <div style={{ textAlign: 'center', padding: '60px 20px', color: 'var(--text3)', fontSize: 13 }}>
              <div style={{ fontSize: 32, marginBottom: 12 }}>🤖</div>
              <div style={{ fontWeight: 600, marginBottom: 6 }}>No AI summary yet</div>
              <div>A summary is generated automatically when an appointment is marked completed.</div>
            </div>
          );

          return (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
              {/* Latest situation — prominent */}
              <div style={{ background: 'linear-gradient(135deg, rgba(15,227,176,0.08), rgba(8,145,178,0.06))', border: '1px solid rgba(15,227,176,0.25)', borderRadius: 12, padding: 20 }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 14 }}>
                  <span style={{ fontSize: 18 }}>🩺</span>
                  <div>
                    <div style={{ fontSize: 13, fontWeight: 700, color: 'var(--mint)' }}>Current Health Situation</div>
                    <div style={{ fontSize: 11, color: 'var(--text3)' }}>
                      From {new Date(latest.appointmentDate).toLocaleDateString()} · Dr. {latest.doctorName}
                    </div>
                  </div>
                </div>
                <p style={{ fontSize: 13.5, lineHeight: 1.65, color: 'var(--text)', margin: '0 0 16px' }}>{latest.summary}</p>
                {latest.keyPoints?.length > 0 && (
                  <ul style={{ margin: 0, paddingLeft: 18, display: 'flex', flexDirection: 'column', gap: 6 }}>
                    {latest.keyPoints.map((kp, i) => (
                      <li key={i} style={{ fontSize: 12.5, color: 'var(--text2)', lineHeight: 1.5 }}>{kp}</li>
                    ))}
                  </ul>
                )}
              </div>

              {/* History */}
              {history.length > 1 && (
                <div>
                  <div style={{ fontSize: 11, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: 'var(--text3)', marginBottom: 12 }}>
                    Previous Summaries
                  </div>
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                    {history.slice(1).map(entry => (
                      <div key={entry._id} style={{ background: 'var(--bg2)', border: '1px solid var(--border)', borderRadius: 10, padding: '14px 16px' }}>
                        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }}>
                          <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text2)' }}>
                            {new Date(entry.appointmentDate).toLocaleDateString()} · Dr. {entry.doctorName}
                          </span>
                          <span style={{ fontSize: 10.5, color: 'var(--text3)' }}>
                            {new Date(entry.generatedAt).toLocaleDateString()}
                          </span>
                        </div>
                        <p style={{ fontSize: 12.5, color: 'var(--text)', margin: '0 0 8px', lineHeight: 1.55 }}>{entry.summary}</p>
                        {entry.keyPoints?.length > 0 && (
                          <ul style={{ margin: 0, paddingLeft: 16 }}>
                            {entry.keyPoints.map((kp, i) => (
                              <li key={i} style={{ fontSize: 11.5, color: 'var(--text3)', lineHeight: 1.5 }}>{kp}</li>
                            ))}
                          </ul>
                        )}
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>
          );
        })()}
      </div>
    </div>
  );
}
